services:
  - type: web
    name: html-to-png-pro
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
